---
- hosts: all 
  gather_facts: yes
  tasks:
  - win_domain_membership:
      workgroup_name: WORKGROUP
      domain_admin_user: psdev\cyclops
      domain_admin_password: '!gu35S%Me)'
      state: workgroup
    register: domain_state
    
  - win_reboot:
    when: domain_state.reboot_required
