---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Power Off VM
    vmware_guest_powerstate:
      hostname: SGDEV-VCSA-01.pspl.phillip.com
      validate_certs: no
      folder: SGDEV/vm
      name: "{{ vm_name }}"
      state: powered-off
  - name: Delete VM
    vmware_guest:
      hostname: SGDEV-VCSA-01.pspl.phillip.com
      validate_certs: no
      name: "{{ vm_name }}"
      state: absent
