---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: create the VM
    vmware_guest:
      hostname: SGDEV-VCSA-01.pspl.phillip.com
      validate_certs: no
      cluster: SGDEV-ESXCLU-01
      datacenter: 'SGDEV'
      folder: SGDEV/vm
      name: "{{ VM_name }}"
      state: poweredon
      guest_id: centos64Guest
      disk:
      - size_gb: 50
        type: None
        autoselect_datastore: yes
      networks:
      - name: Dev Network vlan2
        ip: "{{ ip_address }}"
        netmask: 255.255.255.0
        gateway: "{{ gateway }}"
        dns_servers:
        - 10.30.2.170
        - 10.30.2.158
      hardware:
        memory_mb: "{{ ram }}"
        num_cpus: "{{ core_count }}"
      customization:
        dns_servers:
        - 10.30.2.170
        - 10.30.2.158
        domain : psdev.com
        hostname: "{{ host_name }}"
      template: 'CentosTemplate'
      wait_for_ip_address: yes
 
